article/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from .import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "article"

urlpatterns = [
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("addarticle/", views.addarticle, name = "addarticle"),
    path("article/<int:id>", views.detail, name = "detail"),
    path("update/<int:id>", views.updatearticle, name = "update"),
    path("delete/<int:id>", views.deletearticle, name = "delete"),
    path("", views.articles, name = "articles"),
    path("comment/<int:id>", views.addcomment, name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("about/", views.about, name="about"),
    path("articles/", include("article.urls")),
    path("user/", include("user.urls")),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from .import views

app_name="user"

urlpatterns = [
    path("register/", views.register, name = 'register'),
    path("login/", views.loginUser, name = 'login'),
    path("logout/", views.logoutUser, name = 'logout'),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_photo = models.FileField(blank = True, null = True, verbose_name="Add attachmetn")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name='My Article', related_name='comments')
    comment_author = models.CharField(max_length=50, verbose_name='name')
    comment_content = models.CharField(max_length=200, verbose_name='comment')
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
from django import forms


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_photo"]
    

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "username")
    password = forms.CharField(label = "password", widget=forms.PasswordInput)
    

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label = "Username")
    password = forms.CharField(max_length=20, label = "Password", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, label = "Confirm", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password!=confirm:
            raise forms.ValidationError("Your passwords are not same")
        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.contrib import messages
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.

def articles(request):
    keyword = request.GET.get('keyword')
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles":articles})
    articles = Article.objects.all()

    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

def index(request):
    context = {
        "number1":15
    }
    return render(request, "index.html", context) 

def about(request):
    return render(request, "about.html")

def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)
@login_required(login_url="user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Your article successfully created")
        return redirect("article:dashboard")
    return render(request, "addarticle.html", {"form": form})

def detail(request, id):
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    return render(request, "detail.html", {"article": article, "comments": comments})

@login_required(login_url="user:login")
def updatearticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Your article successfully updated...")
        return redirect("index")
    return render(request, "update.html", {"form": form})

@login_required(login_url="user:login")
def deletearticle(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, "Your article successfully deleted...")
    return redirect("article:dashboard")

def addcomment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == 'POST':
        comment_author = request.POST.get('comment_author')
        comment_content = request.POST.get('comment_content')
        
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()
        return redirect(reverse("article:detail", kwargs = {"id":id}))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages



# Create your views here.
def register(request):
    if request.method=="POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            newUser = User(username=username)
            newUser.set_password(password)

            newUser.save()

            login(request, newUser)
            messages.info(request, 'Successfully registered')

            return redirect("index")
        else:
            context = {
            "form":form
        }
        return render(request, "register.html", context)
    else:
        form = RegisterForm()
        context = {
            "form":form
        }
        return render(request, "register.html", context)





def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username = username, password = password)
        if user is None:
            messages.info(request, "User or password is wrong pls try again")
            return render(request, "login.html", context)
        messages.success(request, "Successfully signed in")
        login(request, user)

        return redirect("index")
    
    return render(request, "login.html", context)

def logoutUser(request):
    logout(request)
    messages.success(request, "You successfully logged out")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}
{% block body %}
<h3 style = "margin-top:100px;">About us</h3>
<hr>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

{% endblock  %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 style = "margin-top:100px;">Create Article</h3>
            <hr>
            <form method="POST" class="post-form" enctype="multipart/form-data">
            <form method = "post">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <button type="submit" class = "btn btn-danger">Save</button>
            </form>
        
        </div>
    </div>

{% endblock  %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}

    <hr>
    <div class="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Articles</h3>
                <hr>
                
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
     
            <form>
                    {% csrf_token %} 
                    <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
                    <button type="submit" class="btn btn-danger">Search</button>
            </form>
            </div>
        </div>
    </div>

            
        
        
    {% if articles %}
        {% for article in articles %}
            <div class="row">
            <div class="col-md-10 offset-md-3">
       
                <!-- Post Content Column -->
                <div class="col-lg-8">

                <!-- Title -->
                <a href = "{% url 'article:detail' article.id %}"> <h2 class="mt-4">{{article.title}}</h2></a>

                <!-- Author -->
                <p class="lead">
                    This article written by: {{article.author.username}}
                </p>
                <hr>
                <!-- Date/Time -->
                <p>{{article.created_date}}</p>
                <hr>

                {% if article.article_photo %}

                <a href = "articles/article/{{article.id}}"><img class = "img-fluid rounded" src = "{{article.article_photo.url}}" alt =""></a>
                    
                {% endif %}

                <!-- Post Content -->
                <p class="lead">{{article.content|safe|truncatewords:10}}</p>
                </p>
                <a style="float:right;" href="/articles/article/{{article.id}}" class = "btn btn-danger">Read more</a>
                        
                <hr>

            </div>
            </div>
            </div>
           {% endfor %}

        {% else %}

        <div class ="row">
            <div class="col-md-10 offset-md-3">
                <div class="col-lg-8">
                    <div class = "alert alert-danger"> We could not find any articles</div>
                </div>
            </div>
        </div>
  
        {% endif %}

        {% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <h3>Dashboard</h3>
    <hr>
    <p>Welcome to your dashboard, <small>{{request.user.username}}</small></p>
    <hr>
    <a class = "btn btn-danger" href = "/articles/addarticle">Addarticle</a>
    <hr>
    {% if articles %}
            <table class="table">
            <thead>
            <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Date</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
            </tr>
            </thead>
                 {% for article in articles  %}
            <tbody>
            <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href = "/articles/article/{{article.id}}">{{article.title}}</a></td>
            <td>{{article.author}}</td>
            <td>{{article.created_date}}</td>
            <td> <a  href="/articles/update/{{article.id}}" class = "btn btn-danger">Update</a></td>
            <td> <a  href="/articles/delete/{{article.id}}" class = "btn btn-danger">Delete</a></td>
            </tr>

            </tbody>

             {% endfor %}
        
        </table>

    
            {% else %}

                <div class = "alert alert-danger">You dont have any articles in your dashboard yet.</div>

            {% endif %}

    

        
       


{% endblock  %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}

<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>
            

        <hr>

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p>

        {% if article.article_photo %}

          <img class = "img-fluid rounded" src = "{{article.article_photo.url}}" alt ="">
      
        {% endif %}

        <hr>
       
        <hr>
        <h4>Comments</h4>
        <hr>

        {% if comments %}

          {% for comment in comments %}

          <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                   <h5 class="mt-0">{{comment.comment_author}}</h5>
                   {{comment.comment_date}}<br>
                   {{comment.comment_content}}
                </div>
          </div>
          
          {% endfor %}
        
          
        {% else %}

          <div class = "alert alert-danger">There is no any comment, be first commenter</div>
        {% endif %}

        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
            {% csrf_token %}

            <div class="form-group">
            <label>Name</label>
            <input name = 'comment_author' type="text" class="form-control"  placeholder="John McCain">
          </div>

              <div class="form-group">
              <label>Your opinion</label>
                <textarea name = 'comment_content' class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

          

        </div>

      </div>



{% endblock  %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{%url 'index' %}">Coder Blog</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About us</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
          </li>
          
        </ul>

            
        <ul class="navbar-nav ml-auto">

          {% if request.user.is_authenticated %}
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'article:dashboard' %}">Dashboard</a>
              </li>


              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
              </li>
          
          {% else %}

            <li class="nav-item active">
                  <a class="nav-link" href="{% url 'user:login'%}">Login</a>
            </li>

            <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register'%}">Create Account</a>
            </li>

          {% endif %}
          
          
        </ul>
        
      </div>
    </nav>

templates/includes/posttemplate.html
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>

templates/index.html
{% extends "layout.html" %}
{% block body %}
    <div style ="margin-top:100px;" class ="jumbotron text-center">
    <h3>Welcome to our BLOG</h3>
    <p>In this blog you may influence the people who need advice with your knowledge and experience</p>
    </div>
        <p>
            {% if request.user.is_authenticated %}
                You are logged in, {{request.user.username}}
            
            {% else %}
                You are not logged in yet...
            {% endif %}





{% endblock  %}

templates/layout.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <title>Document</title>
</head>
<body>

    {% include "includes/navbar.html" %}
    <div style = "margin-top:100px; margin-bottom:100px;" class="container">
    {% if messages %}
        
        {% for message in messages %}
        {% if message.tags == 'info' %}
            <div class='alert alert-danger'>{{ message }}</div>
        {% else %}
            <div class="alert alert-{{message.tags}}">{{ message }}</div>
        {% endif %}
        {% endfor %}
        
    {% endif %}
        {% block body %}
        
        {% endblock  %}
    </div>

    


    <script src="{% static 'js/bootstap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3 style = "margin-top:100px;">Login</h3>
            <hr>

            <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class = "btn btn-danger">Sign in</button>
            </form>
        
        </div>
    </div>

{% endblock body %}

templates/logout.html
{% extends "layout.html" %}
{% block body %}
<h3 style = "margin-top:100px;">Logout</h3>
<hr>
{% endblock  %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 style = "margin-top:100px;">Register</h3>
            <hr>
            <form method = "post">
            {% csrf_token %}
    
            {{form|crispy}}
            <button type="submit" class = "btn btn-danger">Submit</button>
    
            </form>
        
        </div>
</div>









{% endblock  %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 style = "margin-top:100px;">Update</h3>
            <hr>
            <form method="POST" class="post-form" enctype="multipart/form-data">
            <form method = "post">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <button type="submit" class = "btn btn-danger">Update</button>
            </form>
        
        </div>
    </div>

{% endblock  %}